name: Update Tournament Stats

# Define the schedule (run the workflow every hour)
on:
  schedule:
    - cron: '0 0 * * *'  # Runs every hour. Adjust this if needed.

# Define the job
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 3: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the Python script to generate the JSON/HTML
    - name: Run update script
      run: |
        python updated.py

    # Step 5: Commit and push the changes (JSON/HTML file)
    - name: Commit and push updates
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Automated update of tournament stats"
        git push
